### ISSUE TITLE
Repeated error dialog when node mapping missing

### ISSUE THREAD

**Issue by arvestad** [vleandersson/Genvo-Website#4]
If not having a proper prefix/suffix mapping, the dialog explaining that no method to map genes to species worked is shown three times. Then the app is stuck.

Try using the two files cyano.stree and cyano1.gtree that I emailed you.

**Comment by vleandersson** [comment]
This error seems to occure when the genetree are uploded as host and the speciestree as guest. Will se if I can fix it, or limit the options.

**Comment by vleandersson** [comment]
Fixed in the new update (coming later today). Just blocks the faulty input, gives one message for each problem and then returns the user to the index page. This shoulc maybe be done more gracefully in the future
